# Generated by Django 4.2.4 on 2023-09-04 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intrested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('memberes', models.IntegerField()),
                ('address', models.CharField(max_length=500, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packagename', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='package_images')),
                ('description', models.CharField(max_length=1000)),
                ('days', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('pickingdeparture', models.CharField(max_length=300)),
                ('chekingtime', models.TimeField()),
                ('hotelname', models.CharField(max_length=300)),
                ('dayone', models.CharField(max_length=1000)),
                ('daytwo', models.CharField(max_length=300)),
                ('returnairporttime', models.TimeField()),
                ('pickoutdeparture', models.CharField(max_length=300)),
                ('checkouttime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Mytrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dete', models.DateField(auto_now_add=True)),
                ('intrested', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intrestedpackage', to='account.intrested')),
            ],
        ),
        migrations.AddField(
            model_name='intrested',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.packages'),
        ),
        migrations.AddField(
            model_name='intrested',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
