# Generated by Django 4.2.4 on 2023-09-08 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('address', models.CharField(max_length=500, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.packages')),
            ],
        ),
    ]
