# Generated by Django 4.2.4 on 2023-09-10 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_packages_image2_packages_image3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intrested',
            old_name='address',
            new_name='message',
        ),
        migrations.AddField(
            model_name='intrested',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booked',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booked',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intbooked', to='account.packages'),
        ),
    ]
